### ISSUE TITLE
Bad Data Returned from US EPA Ozone to Raw

### ISSUE THREAD

**Issue by Sunoo** [shootismoke/common#48]
It looks like your code uses the 1 hour sampling of Ozone when converting from US EPA. However, aqicn (and maybe others) are returning the 8 hour sampling, so it results in a 0 being returned.

**Comment by amaurymartiny** [comment]
> aqicn (and maybe others) are returning the 8 hour sampling

I had a doubt about this, so went with the 1h sampling a bit randomly, didn't find documentation on aqicn. But you're probably right. Apart from 0 being returned, do you know if there is any documentation about aqicn returning 1h or 8h sampling?

I'll fix this asap! (unless you want to create a PR yourself?)

**Comment by Sunoo** [comment]
I was mostly going by the value being out of range for the 1h formula on all the stations I checked. Although, your reply does raise the possibility that it could vary between 1h and 8h depending on data source, which would be supremely annoying.

I’ll do some digging for documentation, though that has seemed to be pretty sparse so far in my experience.

I’m not sure how it could be easily done, but perhaps the safest way would be to allow for some sort of override between 1h and 8h, though that just shifts the problem to the calling application.

**Comment by Sunoo** [comment]
Found it! They convert all incoming data to 8h averaging.

“The most common averaging is 1 hour. It is also the prefered one, as **our backend system will automatically do the 8 hour averagin computation** for the Ozone and Carbon Monoxyde.”

http://aqicn.org/publishingdata/

**Comment by Sunoo** [comment]
I just forked the project with the intent of creating a PR for this. However, I noticed that the breakpoints already seem to be correct for 8h averaging. I'm a bit at a loss now as to why I'm consistently getting 0 back from your library for the stations in my area, when it should be around 5 or so. All the other pollutants seem to work as expected.

**Comment by amaurymartiny** [comment]
Release in [`@shootismoke/convert@0.2.7`](https://www.npmjs.com/package/@shootismoke/convert/v/0.2.7) 🚀
